# Generated by Django 6.0.5 on 2026-05-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('og_image', models.ImageField(blank=True, upload_to='seo/')),
                ('og_title', models.CharField(blank=True, max_length=60)),
                ('og_description', models.CharField(blank=True, max_length=160)),
                ('canonical_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='StorySiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('og_image', models.ImageField(blank=True, upload_to='seo/')),
                ('og_title', models.CharField(blank=True, max_length=60)),
                ('og_description', models.CharField(blank=True, max_length=160)),
                ('canonical_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
