# Generated by Django 6.0.5 on 2026-05-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutsitesettings_storysitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_meta_title', models.CharField(blank=True, max_length=60, verbose_name='Home Meta Title')),
                ('index_meta_description', models.CharField(blank=True, max_length=160)),
                ('index_og_image', models.ImageField(blank=True, upload_to='seo/')),
                ('index_og_title', models.CharField(blank=True, max_length=60)),
                ('index_og_description', models.CharField(blank=True, max_length=160)),
                ('index_canonical_url', models.URLField(blank=True)),
                ('about_meta_title', models.CharField(blank=True, max_length=60, verbose_name='About Meta Title')),
                ('about_meta_description', models.CharField(blank=True, max_length=160)),
                ('about_og_image', models.ImageField(blank=True, upload_to='seo/')),
                ('about_og_title', models.CharField(blank=True, max_length=60)),
                ('about_og_description', models.CharField(blank=True, max_length=160)),
                ('about_canonical_url', models.URLField(blank=True)),
                ('story_meta_title', models.CharField(blank=True, max_length=60, verbose_name='Story Meta Title')),
                ('story_meta_description', models.CharField(blank=True, max_length=160)),
                ('story_og_image', models.ImageField(blank=True, upload_to='seo/')),
                ('story_og_title', models.CharField(blank=True, max_length=60)),
                ('story_og_description', models.CharField(blank=True, max_length=160)),
                ('story_canonical_url', models.URLField(blank=True)),
                ('products_meta_title', models.CharField(blank=True, max_length=60)),
                ('products_meta_description', models.CharField(blank=True, max_length=160)),
                ('products_og_image', models.ImageField(blank=True, upload_to='seo/')),
                ('products_og_title', models.CharField(blank=True, max_length=60)),
                ('products_og_description', models.CharField(blank=True, max_length=160)),
                ('products_canonical_url', models.URLField(blank=True)),
                ('applications_meta_title', models.CharField(blank=True, max_length=60)),
                ('applications_meta_description', models.CharField(blank=True, max_length=160)),
                ('applications_og_image', models.ImageField(blank=True, upload_to='seo/')),
                ('applications_og_title', models.CharField(blank=True, max_length=60)),
                ('applications_og_description', models.CharField(blank=True, max_length=160)),
                ('applications_canonical_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.DeleteModel(
            name='AboutSiteSettings',
        ),
        migrations.DeleteModel(
            name='IndexSiteSettings',
        ),
        migrations.DeleteModel(
            name='StorySiteSettings',
        ),
    ]
