# Generated by Django 6.0.5 on 2026-05-25 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_delete_aboutsitesettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order in the filter tabs')),
            ],
            options={
                'verbose_name': 'News Category',
                'verbose_name_plural': 'News Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_canonical_url',
            field=models.URLField(blank=True, verbose_name='News Canonical URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='News Meta Description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_meta_title',
            field=models.CharField(blank=True, max_length=60, verbose_name='News Meta Title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_og_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='News OG Description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_og_image',
            field=models.ImageField(blank=True, upload_to='seo/', verbose_name='News OG Image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_og_title',
            field=models.CharField(blank=True, max_length=60, verbose_name='News OG Title'),
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(help_text='Short summary shown on the list page', max_length=300)),
                ('body', models.TextField(help_text='Full article content')),
                ('cover_image', models.ImageField(upload_to='news/covers/')),
                ('read_time', models.PositiveSmallIntegerField(default=3, help_text='Estimated read time in minutes')),
                ('is_featured', models.BooleanField(default=False, help_text='Show this article in the featured slot at the top of the list page')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('og_image', models.ImageField(blank=True, upload_to='news/seo/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='core.newscategory')),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
