# Generated by Django 6.0.5 on 2026-05-25 10:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newscategory_sitesettings_news_canonical_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
