# Generated by Django 6.0.5 on 2026-05-30 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_newsarticle_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50, unique=True, verbose_name='شماره فاکتور')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='اعتبار تا')),
                ('customer_name', models.CharField(max_length=255, verbose_name='نام خریدار')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='شناسه ملی')),
                ('economic_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره اقتصادی')),
                ('register_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره ثبت')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='شهر')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='کد پستی')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='تلفن')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
            },
        ),
        migrations.CreateModel(
            name='FactorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='نام کالا')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='شرح کالا')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='تعداد')),
                ('unit', models.CharField(default='عدد', max_length=30, verbose_name='واحد')),
                ('unit_price', models.BigIntegerField(verbose_name='مبلغ واحد')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.factor')),
            ],
            options={
                'verbose_name': 'آیتم فاکتور',
                'verbose_name_plural': 'آیتم\u200cهای فاکتور',
            },
        ),
    ]
