# Generated by Django 6.0.5 on 2026-05-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_factor_factoritem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='economic_code',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='register_no',
        ),
    ]
