# Generated by Django 6.0.5 on 2026-05-30 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_factor_economic_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50, unique=True, verbose_name='شماره سریال')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='تاریخ اعتبار')),
                ('customer_name', models.CharField(max_length=255, verbose_name='نام مشتری')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='factoritem',
            name='factor',
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='نام کالا')),
                ('description', models.TextField(blank=True, verbose_name='شرح کالا')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='تعداد')),
                ('unit', models.CharField(default='عدد', max_length=30, verbose_name='واحد')),
                ('unit_price', models.BigIntegerField(verbose_name='مبلغ واحد')),
                ('discount', models.BigIntegerField(default=0, verbose_name='تخفیف')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.invoice', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
            },
        ),
        migrations.DeleteModel(
            name='Factor',
        ),
        migrations.DeleteModel(
            name='FactorItem',
        ),
    ]
