# Generated by Django 6.0.5 on 2026-05-30 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0032_alter_category_options'),
        ('core', '0008_invoice_remove_factoritem_factor_invoiceitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product_name',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='نام در فاکتور'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='discount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.invoice'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(default='عدد', max_length=30),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.BigIntegerField(),
        ),
    ]
