# Generated by Django 6.0.5 on 2026-05-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_invoiceitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='desctiprion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
