# Generated by Django 6.0.5 on 2026-05-30 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_invoiceitem_desctiprion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='desctiprion',
            new_name='description',
        ),
    ]
