# Generated by Django 4.2.23 on 2026-06-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_invoice_id_alter_invoiceitem_id_and_more'),
        ('core', '0012_remove_invoiceitem_invoice_and_more'),
    ]

    operations = [
    ]
