# Generated by Django 5.2.16 on 2026-07-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_newsarticle_id_alter_newscategory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_meta_description_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_meta_description_fa',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_meta_title_en',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='About Meta Title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_meta_title_fa',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='About Meta Title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_og_description_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_og_description_fa',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_og_title_en',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_og_title_fa',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='applications_meta_description_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='applications_meta_description_fa',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='applications_meta_title_en',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='applications_meta_title_fa',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='applications_og_description_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='applications_og_description_fa',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='applications_og_title_en',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='applications_og_title_fa',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='index_meta_description_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='index_meta_description_fa',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='index_meta_title_en',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Home Meta Title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='index_meta_title_fa',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Home Meta Title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='index_og_description_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='index_og_description_fa',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='index_og_title_en',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='index_og_title_fa',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_meta_description_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='News Meta Description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_meta_description_fa',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='News Meta Description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_meta_title_en',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='News Meta Title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_meta_title_fa',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='News Meta Title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_og_description_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='News OG Description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_og_description_fa',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='News OG Description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_og_title_en',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='News OG Title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_og_title_fa',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='News OG Title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_meta_description_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_meta_description_fa',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_meta_title_en',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_meta_title_fa',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_og_description_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_og_description_fa',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_og_title_en',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_og_title_fa',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='story_meta_description_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='story_meta_description_fa',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='story_meta_title_en',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Story Meta Title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='story_meta_title_fa',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Story Meta Title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='story_og_description_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='story_og_description_fa',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='story_og_title_en',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='story_og_title_fa',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
