# Generated by Django 5.2.16 on 2026-07-24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_sitesettings_about_meta_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="body_en",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="body_fa",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="excerpt_en",
            field=models.TextField(
                help_text="Short summary shown on the list page",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="excerpt_fa",
            field=models.TextField(
                help_text="Short summary shown on the list page",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="meta_description_en",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="meta_description_fa",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="meta_title_en",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="meta_title_fa",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="title_fa",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="name_fa",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
