# Generated by Django 6.0 on 2026-03-08 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام برند')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='لوگو')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='مثال: کوچک، متوسط، بزرگ، ۶۰×۶۰', max_length=100, verbose_name='برچسب سایز')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='عرض (cm)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='ارتفاع (cm)')),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='عمق / طول (cm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='وزن (kg)')),
            ],
            options={
                'verbose_name': 'ابعاد',
                'verbose_name_plural': 'ابعاد',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام فینیش')),
                ('color', models.CharField(help_text='کد هگز رنگ مثال: #C9A84C', max_length=7, verbose_name='کد رنگ')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'فینیش',
                'verbose_name_plural': 'فینیش\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Products.category')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='زیرعنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیح کوتاه')),
                ('full_description', models.TextField(blank=True, verbose_name='توضیح کامل')),
                ('installments', models.TextField(blank=True, verbose_name='راهنمای نصب')),
                ('wattage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='توان (وات)')),
                ('lumens', models.PositiveIntegerField(blank=True, null=True, verbose_name='شار نوری (لومن)')),
                ('color_temperature', models.PositiveIntegerField(blank=True, null=True, verbose_name='دمای رنگ (کلوین)')),
                ('cri', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='شاخص رنگ\u200cدهی (CRI)')),
                ('beam_angle', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='زاویه تابش (درجه)')),
                ('voltage', models.CharField(blank=True, max_length=50, verbose_name='ولتاژ')),
                ('ip_rating', models.CharField(blank=True, choices=[('IP20', 'IP20 - فضای داخلی'), ('IP44', 'IP44 - مقاوم در برابر پاشش آب'), ('IP54', 'IP54 - مقاوم در برابر گرد و پاشش'), ('IP65', 'IP65 - ضد گرد و جت آب'), ('IP67', 'IP67 - ضد آب (غوطه\u200cوری کوتاه)'), ('IP68', 'IP68 - ضد آب کامل')], max_length=10, verbose_name='درجه حفاظت (IP)')),
                ('dimmable', models.BooleanField(default=False, verbose_name='دیمر پذیر')),
                ('lamp_base_type', models.CharField(blank=True, choices=[('E27', 'E27'), ('E14', 'E14'), ('GU10', 'GU10'), ('GU5.3', 'GU5.3'), ('B22', 'B22'), ('MR16', 'MR16'), ('G9', 'G9'), ('G4', 'G4'), ('other', 'سایر')], max_length=20, verbose_name='نوع سرپیچ')),
                ('lifespan', models.PositiveIntegerField(blank=True, null=True, verbose_name='طول عمر (ساعت)')),
                ('image1', models.ImageField(upload_to='products/', verbose_name='تصویر ۱')),
                ('image1_alt', models.CharField(blank=True, max_length=200, verbose_name='alt تصویر ۱')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='تصویر ۲')),
                ('image2_alt', models.CharField(blank=True, max_length=200, verbose_name='alt تصویر ۲')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='تصویر ۳')),
                ('image3_alt', models.CharField(blank=True, max_length=200, verbose_name='alt تصویر ۳')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='تصویر ۴')),
                ('image4_alt', models.CharField(blank=True, max_length=200, verbose_name='alt تصویر ۴')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO')),
                ('meta_description', models.TextField(blank=True, verbose_name='توضیح SEO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Products.brand', verbose_name='برند')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Products.category', verbose_name='دسته\u200cبندی')),
                ('finishes', models.ManyToManyField(blank=True, related_name='products', to='Products.finish', verbose_name='رنگ\u200cبندی / فینیش')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='مثال: مدل A، کلاسیک، مدرن', max_length=200, verbose_name='نام مدل')),
                ('sku', models.CharField(blank=True, help_text='کد یکتا برای این ترکیب', max_length=100, unique=True, verbose_name='کد محصول (SKU)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('note', models.CharField(blank=True, help_text='هر توضیح اضافی برای این مدل/سایز', max_length=300, verbose_name='یادداشت')),
                ('dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.dimension', verbose_name='ابعاد / سایز')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='Products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مدل / سایز',
                'verbose_name_plural': 'مدل\u200cها / سایزها',
                'ordering': ['model_name'],
                'unique_together': {('product', 'model_name', 'dimension')},
            },
        ),
    ]
