# Generated by Django 6.0 on 2026-03-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='عمق / طول (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='ارتفاع (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='وزن (kg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='عرض (cm)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color_temperature',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='دمای رنگ (کلوین)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='label',
            field=models.CharField(help_text='مثال: کوچک، متوسط، بزرگ، ۶۰×۶۰', max_length=100, null=True, verbose_name='برچسب سایز'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='lumens',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شار نوری (لومن)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='voltage',
            field=models.CharField(blank=True, max_length=50, verbose_name='ولتاژ'),
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='dimension',
        ),
        migrations.DeleteModel(
            name='Dimension',
        ),
    ]
