# Generated by Django 6.0 on 2026-03-08 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_productvariant_unique_together_product_depth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='مثال: کوچک، متوسط، بزرگ، ۶۰×۶۰', max_length=100, verbose_name='برچسب سایز')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='عرض (cm)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='ارتفاع (cm)')),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='عمق / طول (cm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='وزن (kg)')),
            ],
            options={
                'verbose_name': 'ابعاد',
                'verbose_name_plural': 'ابعاد',
                'ordering': ['label'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='wattage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='توان (وات)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.dimension', verbose_name='ابعاد / سایز'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'model_name', 'dimension')},
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='label',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='voltage',
        ),
    ]
