# Generated by Django 6.0 on 2026-03-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_dimension_remove_product_depth_remove_product_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catelog',
            field=models.FileField(blank=True, null=True, upload_to='catelogs/'),
        ),
    ]
