# Generated by Django 6.0 on 2026-03-11 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_product_catelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='installments',
        ),
        migrations.AlterField(
            model_name='product',
            name='catelog',
            field=models.FileField(blank=True, null=True, upload_to='catelogs/', verbose_name='کاتالوگ'),
        ),
        migrations.CreateModel(
            name='Installments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(blank=True, choices=[('1', 'step 1'), ('2', 'step 2'), ('3', 'step 3'), ('4', 'step 4')], max_length=10, null=True, verbose_name='مرحله')),
                ('description', models.CharField(max_length=355, verbose_name='توضیحات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='Products.product', verbose_name='محصول')),
            ],
        ),
    ]
