# Generated by Django 6.0 on 2026-03-11 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_remove_product_installments_alter_product_catelog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(blank=True, choices=[('1', 'step 1'), ('2', 'step 2'), ('3', 'step 3'), ('4', 'step 4')], max_length=10, null=True, verbose_name='مرحله')),
                ('description', models.CharField(max_length=355, verbose_name='توضیحات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment', to='Products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'طریقه نصب',
            },
        ),
        migrations.DeleteModel(
            name='Installments',
        ),
    ]
