# Generated by Django 6.0 on 2026-03-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_installment_delete_installments'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='تایتل'),
        ),
    ]
