# Generated by Django 6.0 on 2026-03-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_installment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='icons/', verbose_name='ایکون'),
        ),
    ]
