# Generated by Django 6.0 on 2026-03-19 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_alter_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام محصول')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='اسلاگ')),
                ('icon', models.ImageField(upload_to='Family')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='فعال')),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True, verbose_name='زیرعنوان')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان SEO')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='توضیح SEO')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families', to='Products.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Products.family'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
