# Generated by Django 6.0 on 2026-04-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_remove_product_brand_family_product_family_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام کاربرد')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ')),
                ('icon', models.FileField(blank=True, null=True, upload_to='applications/icons/', verbose_name='آیکون')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='applications/images/', verbose_name='تصویر کاور')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(blank=True, verbose_name='توضیح کامل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO')),
                ('meta_description', models.TextField(blank=True, verbose_name='توضیح SEO')),
            ],
            options={
                'verbose_name': 'کاربرد (Application)',
                'verbose_name_plural': 'کاربردها',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='family',
            name='icon',
            field=models.ImageField(blank=True, upload_to='Family'),
        ),
        migrations.AddField(
            model_name='product',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='products', to='Products.application', verbose_name='کاربردها'),
        ),
    ]
