# Generated by Django 6.0 on 2026-04-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_application_alter_family_icon_product_applications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='applications',
        ),
        migrations.AddField(
            model_name='family',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='products', to='Products.application', verbose_name='کاربردها'),
        ),
    ]
