# Generated by Django 6.0 on 2026-04-20 16:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_remove_product_applications_family_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='families', to='Products.application', verbose_name='کاربردها'),
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='downloads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'zip', 'rar', 'dwg', 'ies'])])),
                ('file_type', models.CharField(blank=True, choices=[('pdf', 'PDF Document'), ('doc', 'Word Document'), ('xls', 'Excel Spreadsheet'), ('zip', 'ZIP Archive'), ('dwg', 'AutoCAD Drawing'), ('ies', 'IES Photometric File'), ('other', 'Other')], max_length=10)),
                ('file_size', models.CharField(blank=True, editable=False, max_length=20)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='Products.application')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='Products.family')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='Products.product')),
            ],
            options={
                'verbose_name': 'Download',
                'verbose_name_plural': 'Downloads',
                'ordering': ['-created_at'],
            },
        ),
    ]
