# Generated by Django 6.0 on 2026-04-20 16:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_alter_family_applications_download'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='download',
            options={'ordering': ['-created_at'], 'verbose_name': 'فایل دانلودی', 'verbose_name_plural': 'فایل\u200cهای دانلودی'},
        ),
        migrations.AlterField(
            model_name='download',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='Products.application', verbose_name='کاربرد'),
        ),
        migrations.AlterField(
            model_name='download',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='download',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='download',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد دانلود'),
        ),
        migrations.AlterField(
            model_name='download',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='Products.family', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='download',
            name='file',
            field=models.FileField(upload_to='downloads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'zip', 'rar', 'dwg', 'ies'])], verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='download',
            name='file_size',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='حجم فایل'),
        ),
        migrations.AlterField(
            model_name='download',
            name='file_type',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF Document'), ('doc', 'Word Document'), ('xls', 'Excel Spreadsheet'), ('zip', 'ZIP Archive'), ('dwg', 'AutoCAD Drawing'), ('ies', 'IES Photometric File'), ('other', 'Other')], help_text='به صورت خودکار تشخیص داده می\u200cشود', max_length=10, verbose_name='نوع فایل'),
        ),
        migrations.AlterField(
            model_name='download',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='download',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='Products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='download',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='download',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
