# Generated by Django 6.0 on 2026-04-20 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0014_alter_download_options_alter_download_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('content', models.TextField(verbose_name='محتوای کامل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='case_studies/%Y/%m/', verbose_name='تصویر')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='نام مشتری')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='موقعیت')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='تاریخ اتمام')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_studies', to='Products.application', verbose_name='کاربرد')),
                ('products', models.ManyToManyField(blank=True, related_name='case_studies', to='Products.product', verbose_name='محصولات')),
            ],
            options={
                'verbose_name': 'مطالعه موردی',
                'verbose_name_plural': 'مطالعات موردی',
                'ordering': ['-created_at'],
            },
        ),
    ]
