# Generated by Django 6.0 on 2026-04-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0015_casestudy'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mounting_type',
            field=models.CharField(default='afds', max_length=10),
        ),
    ]
