# Generated by Django 6.0 on 2026-04-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0016_product_mounting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
