# Generated by Django 6.0.5 on 2026-05-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0017_category_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='فقط در صورتی پر کنید که این صفحه محتوای تکراری دارد', verbose_name='URL کانونیکال'),
        ),
        migrations.AddField(
            model_name='application',
            name='cover_image_alt',
            field=models.CharField(blank=True, help_text='توضیح تصویر برای موتورهای جستجو و screen readerها', max_length=125, verbose_name='alt تصویر کاور'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='فقط در صورتی پر کنید که این صفحه محتوای تکراری دارد', verbose_name='URL کانونیکال'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='image_alt',
            field=models.CharField(blank=True, help_text='توضیح تصویر برای موتورهای جستجو — حداکثر ۱۲۵ کاراکتر', max_length=125, verbose_name='alt تصویر'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='meta_description',
            field=models.TextField(blank=True, help_text='حداکثر ۱۶۰ کاراکتر', verbose_name='توضیح SEO'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='meta_title',
            field=models.CharField(blank=True, help_text='حداکثر ۶۰ کاراکتر — در صورت خالی بودن، عنوان مطالعه استفاده می\u200cشود', max_length=60, verbose_name='عنوان SEO'),
        ),
        migrations.AddField(
            model_name='category',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='فقط در صورتی پر کنید که این صفحه محتوای تکراری دارد', verbose_name='URL کانونیکال'),
        ),
        migrations.AddField(
            model_name='family',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='فقط در صورتی پر کنید که این صفحه محتوای تکراری دارد', verbose_name='URL کانونیکال'),
        ),
        migrations.AddField(
            model_name='product',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='فقط در صورتی پر کنید که این صفحه محتوای تکراری دارد', verbose_name='URL کانونیکال'),
        ),
        migrations.AlterField(
            model_name='application',
            name='meta_description',
            field=models.TextField(blank=True, help_text='حداکثر ۱۶۰ کاراکتر', verbose_name='توضیح SEO'),
        ),
        migrations.AlterField(
            model_name='application',
            name='meta_title',
            field=models.CharField(blank=True, help_text='حداکثر ۶۰ کاراکتر', max_length=60, verbose_name='عنوان SEO'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, help_text='حداکثر ۱۶۰ کاراکتر — خلاصه\u200cای که در نتایج گوگل نمایش داده می\u200cشود', verbose_name='توضیح SEO'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='حداکثر ۶۰ کاراکتر — در صورت خالی بودن، نام دسته\u200cبندی استفاده می\u200cشود', max_length=60, verbose_name='عنوان SEO'),
        ),
        migrations.AlterField(
            model_name='family',
            name='meta_description',
            field=models.TextField(blank=True, help_text='حداکثر ۱۶۰ کاراکتر', null=True, verbose_name='توضیح SEO'),
        ),
        migrations.AlterField(
            model_name='family',
            name='meta_title',
            field=models.CharField(blank=True, help_text='حداکثر ۶۰ کاراکتر', max_length=60, null=True, verbose_name='عنوان SEO'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1_alt',
            field=models.CharField(blank=True, help_text='توضیح تصویر برای موتورهای جستجو — حداکثر ۱۲۵ کاراکتر', max_length=125, verbose_name='alt تصویر ۱'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2_alt',
            field=models.CharField(blank=True, max_length=125, verbose_name='alt تصویر ۲'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3_alt',
            field=models.CharField(blank=True, max_length=125, verbose_name='alt تصویر ۳'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4_alt',
            field=models.CharField(blank=True, max_length=125, verbose_name='alt تصویر ۴'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, help_text='حداکثر ۱۶۰ کاراکتر', verbose_name='توضیح SEO'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='حداکثر ۶۰ کاراکتر — در صورت خالی بودن، نام محصول استفاده می\u200cشود', max_length=60, verbose_name='عنوان SEO'),
        ),
    ]
