# Generated by Django 6.0.5 on 2026-05-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0018_application_canonical_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationListSiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applications_page_meta_title', models.CharField(blank=True, max_length=60)),
                ('applications_page_meta_description', models.TextField(blank=True, help_text='Keep under 160 characters')),
                ('applications_page_canonical_url', models.URLField(blank=True)),
                ('applications_page_og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='CategoryListSiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_page_meta_title', models.CharField(blank=True, max_length=60)),
                ('categories_page_meta_description', models.TextField(blank=True, help_text='Keep under 160 characters')),
                ('categories_page_canonical_url', models.URLField(blank=True)),
                ('categories_page_og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='ProductListSiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_page_meta_title', models.CharField(blank=True, max_length=60)),
                ('products_page_meta_description', models.TextField(blank=True, help_text='Keep under 160 characters')),
                ('products_page_canonical_url', models.URLField(blank=True)),
                ('products_page_og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
