# Generated by Django 6.0.5 on 2026-05-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0019_applicationlistsitesetting_categorylistsitesetting_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationListSiteSetting',
        ),
        migrations.DeleteModel(
            name='CategoryListSiteSetting',
        ),
        migrations.DeleteModel(
            name='ProductListSiteSetting',
        ),
    ]
