# Generated by Django 6.0.5 on 2026-05-24 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0020_delete_applicationlistsitesetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('location', models.CharField(blank=True, help_text='e.g. Tehran, Iran', max_length=200)),
                ('project_type', models.CharField(blank=True, help_text='e.g. Commercial Complex', max_length=200)),
                ('completion_year', models.CharField(blank=True, help_text='e.g. 2025', max_length=10)),
                ('hero_image', models.ImageField(blank=True, help_text='Full-width hero background image.', null=True, upload_to='projects/heroes/')),
                ('intro_heading', models.CharField(blank=True, help_text="Bold heading below the hero, e.g. 'Premium, Efficient Lighting…'", max_length=300)),
                ('intro_text', models.TextField(blank=True, help_text='Paragraph below the intro heading.')),
                ('overview_text', models.TextField(blank=True, help_text='Body text in the Overview section.')),
                ('about_content', models.TextField(blank=True, help_text='About This Project section. HTML allowed.')),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(blank=True, help_text='Products featured in this project.', related_name='projects', to='Products.product')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-completion_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('file', models.FileField(upload_to='projects/downloads/')),
                ('file_type', models.CharField(blank=True, help_text='Display label, e.g. PDF, DWG.', max_length=20)),
                ('file_size', models.CharField(blank=True, help_text='Human-readable size, e.g. 4.2 MB.', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='Products.project')),
            ],
            options={
                'verbose_name': 'Project Download',
                'verbose_name_plural': 'Project Downloads',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('alt_text', models.CharField(blank=True, help_text='Descriptive alt text for accessibility and SEO.', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='Products.project')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order'],
            },
        ),
    ]
