# Generated by Django 6.0.5 on 2026-05-25 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0021_project_projectdownload_projectgalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Products.application'),
        ),
        migrations.DeleteModel(
            name='CaseStudy',
        ),
    ]
