# Generated by Django 6.0.5 on 2026-05-25 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0022_project_application_delete_casestudy'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Products.application'),
        ),
        migrations.AlterField(
            model_name='project',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='Products.application'),
        ),
    ]
