# Generated by Django 6.0.5 on 2026-05-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0023_product_application_alter_project_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='application',
        ),
    ]
