# Generated by Django 6.0.5 on 2026-05-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0025_alter_family_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='subtitle',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='زیرعنوان'),
        ),
    ]
