# Generated by Django 6.0.5 on 2026-05-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0026_alter_family_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='طول (mm)'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='ارتفاع (mm)'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='label',
            field=models.CharField(blank=True, help_text='مثال: کوچک، متوسط، بزرگ، ۶۰×۶۰', max_length=100, null=True, verbose_name='برچسب سایز'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='عرض (mm)'),
        ),
    ]
