# Generated by Django 6.0.5 on 2026-05-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0027_alter_dimension_depth_alter_dimension_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='label',
            field=models.CharField(blank=True, help_text='مثال: کوچک، متوسط، بزرگ، ۶۰×۶۰', max_length=100, verbose_name='برچسب سایز'),
        ),
    ]
