# Generated by Django 6.0.5 on 2026-05-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0028_alter_dimension_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['number'], 'verbose_name': 'برند', 'verbose_name_plural': 'برندها'},
        ),
        migrations.AddField(
            model_name='family',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
