# Generated by Django 6.0.5 on 2026-05-28 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0029_alter_family_options_family_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['id'], 'verbose_name': 'برند', 'verbose_name_plural': 'برندها'},
        ),
    ]
