# Generated by Django 6.0.5 on 2026-05-28 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0030_alter_family_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['number'], 'verbose_name': 'برند', 'verbose_name_plural': 'برندها'},
        ),
    ]
