# Generated by Django 6.0.5 on 2026-05-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0031_alter_family_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['number'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
    ]
