# Generated by Django 4.2.23 on 2026-06-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0033_alter_application_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='ترتیب نمایش'),
        ),
    ]
