# Generated by Django 4.2.23 on 2026-06-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0034_alter_product_options_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='category/', verbose_name='عکس'),
        ),
    ]
