# Generated by Django 4.2.23 on 2026-06-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0035_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='ترتیب نمایش'),
        ),
    ]
