# Generated by Django 6.0.6 on 2026-07-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0036_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AddField(
            model_name='product',
            name='full_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح کامل'),
        ),
        migrations.AddField(
            model_name='product',
            name='full_description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح کامل'),
        ),
        migrations.AddField(
            model_name='product',
            name='image1_alt_en',
            field=models.CharField(blank=True, help_text='توضیح تصویر برای موتورهای جستجو — حداکثر ۱۲۵ کاراکتر', max_length=125, null=True, verbose_name='alt تصویر ۱'),
        ),
        migrations.AddField(
            model_name='product',
            name='image1_alt_fa',
            field=models.CharField(blank=True, help_text='توضیح تصویر برای موتورهای جستجو — حداکثر ۱۲۵ کاراکتر', max_length=125, null=True, verbose_name='alt تصویر ۱'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2_alt_en',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='alt تصویر ۲'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2_alt_fa',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='alt تصویر ۲'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3_alt_en',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='alt تصویر ۳'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3_alt_fa',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='alt تصویر ۳'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4_alt_en',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='alt تصویر ۴'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4_alt_fa',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='alt تصویر ۴'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='حداکثر ۱۶۰ کاراکتر', null=True, verbose_name='توضیح SEO'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_fa',
            field=models.TextField(blank=True, help_text='حداکثر ۱۶۰ کاراکتر', null=True, verbose_name='توضیح SEO'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='حداکثر ۶۰ کاراکتر — در صورت خالی بودن، نام محصول استفاده می\u200cشود', max_length=60, null=True, verbose_name='عنوان SEO'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title_fa',
            field=models.CharField(blank=True, help_text='حداکثر ۶۰ کاراکتر — در صورت خالی بودن، نام محصول استفاده می\u200cشود', max_length=60, null=True, verbose_name='عنوان SEO'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='نام محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='نام محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='زیرعنوان'),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle_fa',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='زیرعنوان'),
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='download',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='finish',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectdownload',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectgalleryimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
