# Generated by Django 6.0.6 on 2026-07-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0037_product_description_en_product_description_fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cover_image_alt_en',
            field=models.CharField(blank=True, help_text='توضیح تصویر برای موتورهای جستجو و screen readerها', max_length=125, null=True, verbose_name='alt تصویر کاور'),
        ),
        migrations.AddField(
            model_name='application',
            name='cover_image_alt_fa',
            field=models.CharField(blank=True, help_text='توضیح تصویر برای موتورهای جستجو و screen readerها', max_length=125, null=True, verbose_name='alt تصویر کاور'),
        ),
        migrations.AddField(
            model_name='application',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح کامل'),
        ),
        migrations.AddField(
            model_name='application',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح کامل'),
        ),
        migrations.AddField(
            model_name='application',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='حداکثر ۱۶۰ کاراکتر', null=True, verbose_name='توضیح SEO'),
        ),
        migrations.AddField(
            model_name='application',
            name='meta_description_fa',
            field=models.TextField(blank=True, help_text='حداکثر ۱۶۰ کاراکتر', null=True, verbose_name='توضیح SEO'),
        ),
        migrations.AddField(
            model_name='application',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='حداکثر ۶۰ کاراکتر', max_length=60, null=True, verbose_name='عنوان SEO'),
        ),
        migrations.AddField(
            model_name='application',
            name='meta_title_fa',
            field=models.CharField(blank=True, help_text='حداکثر ۶۰ کاراکتر', max_length=60, null=True, verbose_name='عنوان SEO'),
        ),
        migrations.AddField(
            model_name='application',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='نام کاربرد'),
        ),
        migrations.AddField(
            model_name='application',
            name='name_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='نام کاربرد'),
        ),
        migrations.AddField(
            model_name='application',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AddField(
            model_name='application',
            name='short_description_fa',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_fa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='حداکثر ۱۶۰ کاراکتر — خلاصه\u200cای که در نتایج گوگل نمایش داده می\u200cشود', null=True, verbose_name='توضیح SEO'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_fa',
            field=models.TextField(blank=True, help_text='حداکثر ۱۶۰ کاراکتر — خلاصه\u200cای که در نتایج گوگل نمایش داده می\u200cشود', null=True, verbose_name='توضیح SEO'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='حداکثر ۶۰ کاراکتر — در صورت خالی بودن، نام دسته\u200cبندی استفاده می\u200cشود', max_length=60, null=True, verbose_name='عنوان SEO'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title_fa',
            field=models.CharField(blank=True, help_text='حداکثر ۶۰ کاراکتر — در صورت خالی بودن، نام دسته\u200cبندی استفاده می\u200cشود', max_length=60, null=True, verbose_name='عنوان SEO'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='حداکثر ۱۶۰ کاراکتر', null=True, verbose_name='توضیح SEO'),
        ),
        migrations.AddField(
            model_name='family',
            name='meta_description_fa',
            field=models.TextField(blank=True, help_text='حداکثر ۱۶۰ کاراکتر', null=True, verbose_name='توضیح SEO'),
        ),
        migrations.AddField(
            model_name='family',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='حداکثر ۶۰ کاراکتر', max_length=60, null=True, verbose_name='عنوان SEO'),
        ),
        migrations.AddField(
            model_name='family',
            name='meta_title_fa',
            field=models.CharField(blank=True, help_text='حداکثر ۶۰ کاراکتر', max_length=60, null=True, verbose_name='عنوان SEO'),
        ),
        migrations.AddField(
            model_name='family',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام محصول'),
        ),
        migrations.AddField(
            model_name='family',
            name='name_fa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام محصول'),
        ),
        migrations.AddField(
            model_name='family',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='زیرعنوان'),
        ),
        migrations.AddField(
            model_name='family',
            name='subtitle_fa',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='زیرعنوان'),
        ),
        migrations.AddField(
            model_name='project',
            name='about_content_en',
            field=models.TextField(blank=True, help_text='About This Project section. HTML allowed.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='about_content_fa',
            field=models.TextField(blank=True, help_text='About This Project section. HTML allowed.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='intro_heading_en',
            field=models.CharField(blank=True, help_text="Bold heading below the hero, e.g. 'Premium, Efficient Lighting…'", max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='intro_heading_fa',
            field=models.CharField(blank=True, help_text="Bold heading below the hero, e.g. 'Premium, Efficient Lighting…'", max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='intro_text_en',
            field=models.TextField(blank=True, help_text='Paragraph below the intro heading.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='intro_text_fa',
            field=models.TextField(blank=True, help_text='Paragraph below the intro heading.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='location_en',
            field=models.CharField(blank=True, help_text='e.g. Tehran, Iran', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='location_fa',
            field=models.CharField(blank=True, help_text='e.g. Tehran, Iran', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description_fa',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_title_fa',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='name_fa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='overview_text_en',
            field=models.TextField(blank=True, help_text='Body text in the Overview section.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='overview_text_fa',
            field=models.TextField(blank=True, help_text='Body text in the Overview section.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type_en',
            field=models.CharField(blank=True, help_text='e.g. Commercial Complex', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type_fa',
            field=models.CharField(blank=True, help_text='e.g. Commercial Complex', max_length=200, null=True),
        ),
    ]
