# Generated by Django 6.0.6 on 2026-07-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0038_application_cover_image_alt_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='persian_image',
            field=models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='persian image'),
        ),
    ]
