# Generated by Django 6.0.6 on 2026-07-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0039_category_persian_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='حداکثر ۶۰ کاراکتر — در صورت خالی بودن، نام محصول استفاده می\u200cشود', max_length=90, verbose_name='عنوان SEO'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='حداکثر ۶۰ کاراکتر — در صورت خالی بودن، نام محصول استفاده می\u200cشود', max_length=90, null=True, verbose_name='عنوان SEO'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title_fa',
            field=models.CharField(blank=True, help_text='حداکثر ۶۰ کاراکتر — در صورت خالی بودن، نام محصول استفاده می\u200cشود', max_length=90, null=True, verbose_name='عنوان SEO'),
        ),
    ]
