# Generated by Django 6.0.6 on 2026-07-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0040_alter_product_meta_title_alter_product_meta_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='حداکثر ۶۰ کاراکتر — در صورت خالی بودن، نام دسته\u200cبندی استفاده می\u200cشود', verbose_name='عنوان SEO'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='حداکثر ۶۰ کاراکتر — در صورت خالی بودن، نام دسته\u200cبندی استفاده می\u200cشود', null=True, verbose_name='عنوان SEO'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title_fa',
            field=models.CharField(blank=True, help_text='حداکثر ۶۰ کاراکتر — در صورت خالی بودن، نام دسته\u200cبندی استفاده می\u200cشود', null=True, verbose_name='عنوان SEO'),
        ),
    ]
