# Generated by Django 6.0.6 on 2026-07-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0041_alter_category_meta_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='meta_title',
            field=models.CharField(blank=True, help_text='حداکثر ۶۰ کاراکتر', null=True, verbose_name='عنوان SEO'),
        ),
        migrations.AlterField(
            model_name='family',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='حداکثر ۶۰ کاراکتر', null=True, verbose_name='عنوان SEO'),
        ),
        migrations.AlterField(
            model_name='family',
            name='meta_title_fa',
            field=models.CharField(blank=True, help_text='حداکثر ۶۰ کاراکتر', null=True, verbose_name='عنوان SEO'),
        ),
    ]
