# Generated by Django 6.0.6 on 2026-07-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0042_alter_family_meta_title_alter_family_meta_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='icon_alt',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='meta_title',
            field=models.CharField(blank=True, null=True, verbose_name='عنوان SEO'),
        ),
        migrations.AlterField(
            model_name='family',
            name='meta_title_en',
            field=models.CharField(blank=True, null=True, verbose_name='عنوان SEO'),
        ),
        migrations.AlterField(
            model_name='family',
            name='meta_title_fa',
            field=models.CharField(blank=True, null=True, verbose_name='عنوان SEO'),
        ),
    ]
