# Generated by Django 6.0.6 on 2026-07-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0043_family_icon_alt_alter_family_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='icon_alt_en',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='icon_alt_fa',
            field=models.CharField(blank=True, null=True),
        ),
    ]
