# Generated by Django 6.0.6 on 2026-07-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0044_family_icon_alt_en_family_icon_alt_fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hover_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
